### ISSUE TITLE
Yield content inside

### ISSUE THREAD

**Issue by pablogravielseo** [st-h/ember-content-editable#111]
Hello, I wonder if is possible to yield a content inside of the content editable, I want to use an element inside with the attribute "contenteditable="false", I would like to use like in this way:

```
<div class="a" contenteditable="true">
   <div class="b" contenteditable="false">
       <img src="url here">
   </div><br>
   text goes here
</div>
```

**Comment by st-h** [comment]
sorry about the late reply. I wonder why you would like to nest contenteditable elements, however, this is not supported by this addon. 

Yet, the upcoming release of this addon will be based on https://github.com/st-h/ember-content-editable-modifier which allows to turn any element into a contenteditable element by applying an ember modifier. You should be able to easily build your own contenteditable component based on the modifier and your specific needs.
