### ISSUE TITLE
Disabled attribute still doesn't work

### ISSUE THREAD

**Issue by wesleyks** [st-h/ember-content-editable#117]
Hi, so this issue was supposedly fixed in #109 but it seems that the input is still editable when `@disabled={{true}}`. What I think is happening is that the styles in `ember-content-editable-modifier` are still targeting `.ember-content-editable` instead of `.ember-content-editable[contenteditable]` so then `-webkit-user-modify: read-write-plaintext-only;` still gets applied.

**Comment by st-h** [comment]
Thank you. Could you please give `4.0.0-rc.4` a try?
