### ISSUE TITLE
paste & input events.

### ISSUE THREAD

**Issue by coulix** [st-h/ember-content-editable#12]
handlePaste is called to check against max length.
It would be handy to an action `key-paste` event triggered.

Same for the `input` event.

**Comment by hectorh30** [comment]
Or maybe an `on-paste` event

**Comment by joshuairl** [comment]
Would love to see this, pasting from Excel and things turns into garbage.  If anyone could give me a quick high level overview of the basics of how it should be implemented I don't mind contributing to adding it.

**Comment by st-h** [comment]
@joshuairl I am a little unsure about the edit history of your post, but yes - I think we can add a hook for paste events to the 1.0.0 release of the addon.

**Comment by joshuairl** [comment]
Sorry!
I basically converted my post into my explanation for future visitors on how it could be implemented in their app without the plugin being edited.

Just more of a reference.

--
Joshua F. Rountree | UX Developer
The E.W. Scripps Company
312 Walnut Street, Suite 2800, Floor 29th, Office 29W109
Cincinnati, Ohio 45202-4024
(513) 977-3840 (office, M-F, 7a-4p)
(513) 827-7936 (mobile)

**Comment by st-h** [comment]
@joshuairl ah, thanks for the input. Added a paste hook to the 1.0.0 release.
