### ISSUE TITLE
Pasted Text is not displayed as plain-text but rather with formatting.

### ISSUE THREAD

**Issue by heeren-cliqz** [st-h/ember-content-editable#23]
Package version: 0.9.0
Summary:
I have a content-editable tag

```
{{content-editable value=article.domain
                       placeholder="Article Domain"
                       disabled=article.editableDisabled
                       enter='handleEnter'
                       escape-press='handleEsc'
                       type="text"
                       tagName="span"}}
```

When I am copying a paste with a website and putting this inside its coming with all the formatting as shown in the picture below {To show this issue, please look at topmost container. Rest of the content-editable tags are same}.
![screen shot 2016-07-22 at 09 51 51](https://cloud.githubusercontent.com/assets/9553158/17050267/35a96136-4ff2-11e6-8156-40a6c89e2258.png)

Though when I reload the page then this formatting is gone and its been displayed like a plain text in that field.

**Comment by st-h** [comment]
should be fixed in `1.0.0`
