### ISSUE TITLE
placeholder not works in ember 2.7.0

### ISSUE THREAD

**Issue by nightire** [st-h/ember-content-editable#25]
These styles will not works any more:

https://github.com/AddJam/ember-content-editable/blob/master/addon/styles/addon.css#L1-L4

Not sure why, but if you change `[contenteditable=true]` to `.ember-content-editable` or any other class name that user specified, placeholder will works again.

**Comment by danidr** [comment]
Hello,
Looks like this bug is back. Adding the "placeholder" property doesn't do anything.
I have checked the merge referenced here, but my CSS is updated as per merge; still, the placeholder doesn't work. I am running on Ember 2.11.
Any ideas?

**Comment by st-h** [comment]
Hey @nightire. I have taken over this addon. I am not aware of any issues with the last ember versions when using placeholders. Would you mind opening a new issue if this still is a problem as this issue is a year old by now.
