### ISSUE TITLE
type "html" doenst work

### ISSUE THREAD

**Issue by cahyowhy** [st-h/ember-content-editable#31]
i am trying to insert value with my custom tag but it doesnt work
`{{content-editable value=message placeholder=(t 'placeholder.input.message') tagName="span" enter='doSend' type="html"}}`
![dawewd](https://cloud.githubusercontent.com/assets/18083469/26192345/7b9783be-3bdb-11e7-83c3-83cd2ca9ada2.JPG)

**Comment by st-h** [comment]
@cahyowhy are you actually trying to render html? that would introduce possible xss security issues and some more dangerous stuff.

from the docs:
> text strips out any html tags, html doesn't.

the screenshot looks like html is not stripped out, so everything works as expected. Please reopen if this should not be the case.
