### ISSUE TITLE
Adding maxlength fixes text convert issue

### ISSUE THREAD

**Issue by dgavey** [st-h/ember-content-editable#33]
On the bug I found, I was using a type='text' editable field and when I pasted data from an HTML (or doc with formatting) it was being persevered, instead of converting to text.  Adding a maxlength=10000 fixed the conversion issue.

On the opposite issue though, if I have a type='html' and a maxlength the HTML is stripped in the editor field. Mostly putting this if someone else comes across it.

Was wondering if this project has been abandoned?  I would like to modernize it and fix a few bugs, but was wondering if I did a PR if it would be accepted still?  If not, I'd be happy to fork it.

**Comment by chrissloey** [comment]
Hey @dgavey. We're not maintaining this anymore.

If you or someone else wants to maintain it we'd be happy to add a link to a fork in the readme.

**Comment by st-h** [comment]
@dgavey I have created the [1.0.0-rewrite](https://github.com/st-h/ember-content-editable/tree/1.0.0-rewrite) branch, which removes observers, computed properties, deprecations etc and makes use of the newer component api. Please feel free to contribute refactorings and fixes to this branch which don't fit into the 0.x releases. The 0.11.x releases will most likely be the last of the 0.x series, which just updates dependencies and fixes critical bugs and issues (in case there even are any).

**Comment by st-h** [comment]
should be fixed in `1.0.0`
