### ISSUE TITLE
ember-content-editable future?

### ISSUE THREAD

**Issue by st-h** [st-h/ember-content-editable#34]
As this addon is labeled unmaintained, are there any plans for the future? Were there any technical issues that lead to this decision? And lastly, is there any interest in transferring ownership? It's kind of sad to see this addon die.

**Comment by chrissloey** [comment]
Hey @st-h, thank you for asking this, I should have probably made an issue about it. The decision was just based on our time and needs - we're a very small company and we don't use Ember in any of our current projects.

If you or anyone else would like to maintain the project, I'd be happy to transfer ownership.

**Comment by st-h** [comment]
@chrissloey thanks for the fast reply. I would like to help out. Don’t have too much time myself, but at least would like to make sure dependencies are updated and current functionality is maintained.

**Comment by chrissloey** [comment]
@st-h Ok cool. I'll leave this issue open until tomorrow to see if others are also interested in maintaining along with you then I'll transfer ownership.

**Comment by st-h** [comment]
👍 sounds good. In case someone comes along later that shouldn't be much of an issue. I just want to keep this addon alive in the communities interest and don't see any point in releasing a new one when there already is one that works.

**Comment by chrissloey** [comment]
@st-h started the transfer to you (had to transfer it to myself first).

**Comment by st-h** [comment]
@chrissloey great, thanks you. Already managed to do some work today. Would you mind adding me ( https://www.npmjs.com/~st-h ) as an owner in npm as well? Otherwise there does not seem to be a way to publish new releases without you doing some work. https://docs.npmjs.com/cli/owner

```
npm owner ls ember-content-editable
addjam <team@addjam.com>
```

**Comment by st-h** [comment]
@chrissloey Don't mean to bother you, but if there is anything I can do to help get this resolved, please let me know.

**Comment by chrissloey** [comment]
@st-h Sorry! Didn't see the previous post. Will take a look.

**Comment by chrissloey** [comment]
@st-h Done 😄

**Comment by st-h** [comment]
@chrissloey awesome! 👍  looks like we have a release 💯
