### ISSUE TITLE
placeholder not working on Edge - 1.0.0.alpha-3

### ISSUE THREAD

**Issue by danidr** [st-h/ember-content-editable#41]
Hello,
I have updated to Alpha 3 for a project I'm working on, but on Edge, instead of setting the placeholder in case the value is null, it will just show "null" as a content. Works fine on Safari and Chrome.
Will roll back to pre-1.0.0 since it I am on a release cycle.

**Comment by st-h** [comment]
Thank you for reporting this. Would you please mind verifying this on the [demo page](http://st-h.github.io/ember-content-editable/)?
I added two fields to the bottom of the page, which have undefined and null as value and a placeholder set. Both work fine using the edge 41 VM provided by microsoft as seen here: ![edge](https://github.com/st-h/ember-content-editable/raw/gh-pages/Capture.PNG)

both placeholder seem to render correctly. Links to source: [template](https://raw.githubusercontent.com/st-h/ember-content-editable/1.0.0-rewrite/tests/dummy/app/templates/application.hbs),  [controller](https://raw.githubusercontent.com/st-h/ember-content-editable/1.0.0-rewrite/tests/dummy/app/controllers/application.js)

Does this only affect specific versions of edge or are you seeing an entirely different issue? 

The 1.0.0 rewrite did not really touch anything related to placeholders, however I probably might have overlooked something. But this will be difficult to fix unless we have a way to reproduce.

**Comment by danidr** [comment]
Just tested it on Edge, v. 40.15063.674.0, HTML 15.15063. This is what I have
<img width="1421" alt="null-edge" src="https://user-images.githubusercontent.com/1716741/35728545-320328e0-080c-11e8-839c-83fc9a0d299c.png">
Apparently, null value DOES mess up with Edge...

**Comment by st-h** [comment]
@danidr would you mind checking alpha.4 regarding this? I might have had an idea what might be causing this, even though it seems a little strange that this only appears in certain browser versions.

**Comment by danidr** [comment]
Tried the demo page on Edge again, and the placeholder now appears correctly. Thanks for the quick fix!
