### ISSUE TITLE
Pass though "dir" attribute

### ISSUE THREAD

**Issue by krukid** [st-h/ember-content-editable#61]
The component currently does not allow setting "dir" attribute, which would be useful for many rtl/ltr/bidi cases, especially since you can only set "auto" direction via this attribute.

**Comment by st-h** [comment]
I will see if I can find time to implement this, otherwise PRs are very welcome!

**Comment by st-h** [comment]
sorry about the late reply. This should be now fixed in version 3.0.0 where you can pass any attribute. Upgrades require to migrate due to two way binding no longer being available with current ember versions.
